### PR TITLE
Ride Assignment View in Table

### LINKED ISSUE #3: FEATURE: Rider can see whether their ride request is assigned or not
### As a...

Rider

### I can...

See whether or not my ride has been assigned to a driver or not

### So that...

I don't get confused if a ride request I made was seen or not

### Discussion

Right now riders have no way of telling if their ride request was assigned to a shift or not. The ride is left in the dark, and this has the potential to lead to confusion: maybe the driver goes to pick them up and the rider assumed that the requests was not taken on, or the rider waits for a driver but the request was never seen.

image

What we want is some indication to the rider that the ride request will be taken on.

I think an acceptable way to do this is to simply have a table column on the ride request table for riders, that indicated whether that request has been assigned or not. This could be either text that says `Assigned` or `Unassigned` or a checkbox.

### Acceptance Criteria

- [ ] Rider can see whether their request is assigned by viewing their list of ride requests.

### Implementation Todos

Frontend:
- [ ] In `RideTable.js` modify the `columnsRider` to include a column that show whether a ride request is assigned or not. A shiftId of 0 indicated unassigned and anything else is assigned.

### PR DESCRIPTION
**Pull request by tejasvissa813**
Currently, when a user created a ride request, they could never go back and check whether or not their request has been fulfilled which could lead to a lot of anxiety from the customer. I modified the RidesTable component as shown below so that whenever a ride is created the rider can check the status of the ride through the status column of the table

Screenshot 2024-05-26 at 1 52 56 PM
[This shows the table from a riders perspective before the ride is assigned by an admin account]

Screenshot 2024-05-26 at 1 54 35 PM
[This is the updated table once the ride has been assigned]

Closes #3

### CODE REVIEW

**Review by Ononymous — DISMISSED** [review]
LGTM, but make sure to add more description to PR, so everybody reading it can understand it immediately. For example, use As, I can, and So that format.

**Review by pconrad — CHANGES_REQUESTED** [review]
I have a question: this relies on a field being in the Ride json.

Does that field exist in the json returned by the backend?

* If not, you'll need a different approach.
* If so, then you should be able to show this working on a dokku deployment.

**Comment by tejasvissa813** [comment]
I realized that my backend changes didn't get pushed to my branch since I called git add from my frontend folder.

**Review by pconrad — CHANGES_REQUESTED** [review]
The code looks fine... but when I deploy this I don't see the new column on the table.

Can you make a more clear test plan?

**Review by pconrad — APPROVED** [review]

**Pull request merged**
