### PR TITLE
Change the driver id into dropdowns in shift form

### LINKED ISSUE #14: FEATURE: Change Driver Id text fields to dropdown
# User Story

*  As an Admin
* I can select a driver from a dropdown
* So that I dont have to memorize driver ids

### Discussion

Right now, when admins are creating shifts, the form contain text boxes where the admin has to input the `Driver Id`.

image

This is inconvenient because, the admin either has to memorize witch driver id corresponds to which person, check it beforehand, or if they don't remember while filling out the form, they have to check and potentially lose progress.

It would be much easier to be able to select from a dropdown list that contains all of the active driver ids and their names.

### Acceptance Criteria

- [ ] When creating shifts, an admin can select the `Driver ID` and `Backup Driver ID` from a dropdown containing all of the drivers

### Implementation Todos

Frontend:
- [ ] Modify `ShiftForm.js` to use the backend `DriversController.java` get all endpoint to get a list of all drivers and use it to populate a dropdown.

### PR DESCRIPTION
**Pull request by Ononymous**
- As an Admin
- I can select a driver from a dropdown
- So that I dont have to memorize driver ids

image

Was very inconvenient since admin needs to remember the driver ids and put them in as text manually.

Now admin would be able to select a driver from the dropdown, with their names displayed. No longer have to remember driver ids.

added useBackend in shiftForm, changed shiftForm, shiftEditPage, shiftCreatePage tests to pass stryker and coverage

Closes #14

### CODE REVIEW

**Review by Tommygithubaccount123 — APPROVED** [review]
LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
Can you improve the PR description?

See: https://ucsb-cs156.github.io/topics/pull_requests/#pr-descriptions
 
The screenshot is helpful, but a little bit of explanation would go a long way. 

You can copy/paste from the issue if that helps.

**Comment by Ononymous** [comment]
> Can you improve the PR description?
> 
> See: https://ucsb-cs156.github.io/topics/pull_requests/#pr-descriptions
> 
> The screenshot is helpful, but a little bit of explanation would go a long way.
> 
> You can copy/paste from the issue if that helps.

Added non-technical description about the change.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
